spring.application.name=secureops-backend
spring.datasource.url=jdbc:postgresql://localhost:5432/secureops
spring.datasource.username=postgres
spring.datasource.password=Ashmitha

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true